module.exports = {
  content: ["./src/frontend/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "primary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b9c7e0",
        "on-surface": "#0b1c30",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-container": "#f39461",
        "on-secondary-fixed": "#0d1c2f",
        "on-secondary-fixed-variant": "#3a485c",
        "secondary-container": "#d5e3fd",
        "on-surface-variant": "#444651",
        "error": "#ba1a1a",
        "on-primary-container": "#90a8ff",
        "on-secondary-container": "#57657b",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#ffb691",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "secondary": "#515f74",
        "on-tertiary-fixed-variant": "#773205",
        "tertiary-fixed": "#ffdbcb",
        "surface-dim": "#cbdbf5",
        "inverse-primary": "#b6c4ff",
        "primary-fixed-dim": "#b6c4ff",
        "primary": "#00236f",
        "surface-container-high": "#dce9ff",
        "inverse-surface": "#213145",
        "outline-variant": "#c5c5d3",
        "outline": "#757682",
        "background": "#f8f9ff",
        "surface-tint": "#4059aa",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#341100",
        "on-primary": "#ffffff",
        "tertiary": "#4b1c00",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#d5e3fd",
        "on-primary-fixed": "#00164e",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#6e2c00",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary-container": "#1e3a8a",
        "surface-variant": "#d3e4fe"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        xl: "32px",
        gutter: "16px",
        md: "16px",
        unit: "4px",
        "container-margin": "24px",
        lg: "24px",
        sm: "8px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "h1-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "h1-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }]
      }
    }
  }
};
